# Generated by Django 5.2.1 on 2025-05-12 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField()),
                ('ShipDate', models.DateField()),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerce.customerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField()),
                ('PaymentAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMethod', models.CharField(max_length=255)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerce.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductDescription', models.TextField()),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductUnits', models.CharField(max_length=255)),
                ('ProductSize', models.CharField(max_length=255)),
                ('ProductColor', models.CharField(max_length=255)),
                ('owner', models.CharField(default='admin1', max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerce.category')),
            ],
            options={
                'unique_together': {('ProductName', 'category')},
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('OrderItemsID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerce.orders')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eccomerce.products')),
            ],
        ),
    ]
