# Generated by Django 5.2.1 on 2025-05-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0002_remove_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.CharField(default='admin1', max_length=255),
        ),
    ]
